### ISSUE TITLE
download error 

### ISSUE THREAD

**Issue by smmya** [2niuhe/jable_downloader#11]
error log:
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from executor import process_subscription, process_videos
  File "/opt/jable_downloader/executor.py", line 59
SyntaxError: Non-ASCII character '\xe5' in file /opt/jable_downloader/executor.py on line 59, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by 2niuhe** [comment]
You should use python3

**Comment by smmya** [comment]
> You should use python3

thanks
