### ISSUE TITLE
下载无反应

### ISSUE THREAD

**Issue by letterk** [2niuhe/jable_downloader#12]
python main.py videos https://jable.tv/videos/mogi-061/
Traceback (most recent call last):
  File "E:\_Downloads\_BT\av\jable_downloader\main.py", line 36, in <module>
    args.func(args)
  File "E:\_Downloads\_BT\av\jable_downloader\executor.py", line 145, in process_videos
    video_crawler.download_by_video_url(video_url)
  File "E:\_Downloads\_BT\av\jable_downloader\video_crawler.py", line 106, in download_by_video_url
    page_res = utils.cloudscraper_requests_get(url, retry=5)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\_Downloads\_BT\av\jable_downloader\utils.py", line 76, in cloudscraper_requests_get
    time.sleep(120 * i)
KeyboardInterrupt

设置了token也不见消耗

**Comment by 2niuhe** [comment]
@letterk 网站更新反爬机制了，需要拉最新的代码

**Comment by letterk** [comment]
> 你代码是旧版本的实现了

最新的代码, 依然不行

**Comment by 2niuhe** [comment]
最新代码不会报这个错的，cloudscraper_requests_get函数在新代码里都被删掉了

**Comment by letterk** [comment]
Unexpected Error: HTTPSConnectionPool(host='api.scrapingant.com', port=443): Max retries exceeded with url: /v2/general?url=https%3A%2F%2Fjable.tv%2Fvideos%2Fssis-668%2F&x-api-key=e66760f97d184daf80d6f23fa7d663cd&browser=false (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)))

**Comment by 2niuhe** [comment]
@letterk 应该是网站又改了反爬策略，你在config.json里，配置一下sa_mode就可以了

```json
"sa_token": "your token here"
"sa_mode": "browser"
```

**Comment by letterk** [comment]
设置了"browser"就正常了
