### ISSUE TITLE
ffmpeg使用硬件加速的方式进行解码和转码

### ISSUE THREAD

**Issue by Magical-Lin** [2niuhe/jable_downloader#13]
首先，转码一遍后拖进度条播放确实不卡了。
使用`ffmpeg -hwaccels`命令查看支持的硬件加速选项
下面我使用cuvid的选项，以H.264解码后转码H.265
`ffmpeg -hwaccel cuvid -c:v h264_cuvid -i .\DNJR-081.mp4 -c:v hevc_nvenc  -y .\DNJR-081.mkv`
笔记本端GTX3060转码1.8G两小时时长视频耗时3分钟，参数说明
-hwaccel cuvid：指定使用cuvid硬件加速
-c:v h264_cuvid：使用h264_cuvid进行视频解码
-c:v h264_nvenc：使用h264_nvenc进行视频编码
这两种编码方式可以运行`ffmpeg -codecs`输出到管道过滤 cuvid查到，decoders为解码输入参数，encoders是编码输入参数
H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_qsv h264_cuvid ) (encoders: libx264 libx264rgb h264_amf h264_mf h264_nvenc h264_qsv )

 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_qsv hevc_cuvid ) (encoders: libx265 hevc_amf hevc_mf hevc_nvenc hevc_qsv )

另外，快速编码H.265
ffmpeg -hwaccel cuvid  -i DNJR-081.mp4 -vcodec hevc_nvenc -y DNJR-081-h265.mp4

**Comment by Magical-Lin** [comment]
有一个问题就是GPU加速转码的视频不仅没减少，反而文件变大了。
还是要用房主提供的CPU方式压缩，缺点就是电脑跑满CPU，要卡一段时间，笔记本风扇疯狂转，声音很大
 h265编码压缩视频(体积可以减少为原1/3，实测1.8G的视频可以压缩到500M，耗时30分钟)
ffmpeg -i DNJR-081.mp4 -c:v libx265 -vtag hvc1 -c:a copy DNJR-081-h265.mkv

**Comment by Magical-Lin** [comment]
兄弟们，我整个人麻了，网上关于CPU和GPU加速压制视频的讨论有很多，看完后总结刷新我的认知，我一直以为显卡加速压制最好，没想到。。。。gpu压制相比cpu压制会极大损失画质，cpu 和gpu 压制视频的质量是存在肉眼可见的差异的，cpu 压制的明显好于gpu 压制的，文件也会更小。但是CPU压制时间真的太久了,笔记本也呼呼响，而GPU只要两三分钟。
兄弟们，把你们压制视频的情况也说一下吧

**Comment by 2niuhe** [comment]
可以看看这个讨论：https://github.com/hcjohn463/JableTVDownload/issues/96
