### ISSUE TITLE
請求下載檔案合併後，自動建立資料夾進入該資料夾，檔案標題只有番號

### ISSUE THREAD

**Issue by Dissyu** [2niuhe/jable_downloader#2]
作者您好，

感謝你製作出優質的下載器，想請求作者能夠做出一版，檔案合併後，建立番號資料夾，

並且將檔案放進去，資料夾名稱和檔案的檔名只有番號這種就可以，

謝謝~

**Comment by 2niuhe** [comment]
@Dissyu 

更新了一版，支持输出格式   番号/番号.mp4

使用方式：
可以config.json文件中配置输出格式:

```
    "outputFileFormat": "id/id.mp4",
```

https://github.com/2niuhe/jable_downloader/blob/a4494f493b106c4b5fd5f4d4bfe982b261a02d70/README.md?plain=1#L85
