### ISSUE TITLE
下載速度異常

### ISSUE THREAD

**Issue by Dissyu** [2niuhe/jable_downloader#3]
Hello 作者

非常感謝你製作出優良的作品，由衷感激

這邊遇到一個問題，常常下載一半會停住不動，大概過了5分鐘左右，然後又會繼續跑下載

請問這方面的問題會是什麼嗎

謝謝

**Comment by 2niuhe** [comment]
@Dissyu 

出现卡住等一会继续下载的原因是，向服务器请求视频资源的时候，**请求过于频繁，服务器拒绝访问了，所以程序中设置了延时重试的机制来增大下载的成功率**。所以卡住实际上是延时重试，第一次重试延迟120s，第二次重试延迟240s，延迟时间依次递增，最多重试5次。
