### ISSUE TITLE
作者您好, Jable一个视频包含多个标签，如果不同标签出现同一个视频，爬虫会下载还是跳过重复呢？

### ISSUE THREAD

**Issue by sewujishipin** [2niuhe/jable_downloader#8]
作者您好, Jable一个视频包含多个标签，如果不同标签出现同一个视频，爬虫会下载还是跳过重复呢？

比如一个视频 有 标签A 标签B  标签C    我在爬虫添加订阅 ABC 但是其中一个视频三个标签都包含，是不是会下载三次？

**Comment by 2niuhe** [comment]
@sewujishipin 

程序有检测重复的机制，检测机制**会判断你配置的下载路径**下有没有已经下载了的文件，所以只会下载一次，发现视频已经被下载，会跳过。

所以你没有把视频从下载路径移动到其他位置的话，是不会重复下载的。

**Comment by 2niuhe** [comment]
> @2niuhe 作者你好，我的是这个意思，[中文字幕] [直接**] [處女作/引退作][美*] [熟女][人妻] [短髮][顏*] jable的分类是根据视频下方标签来分类检索的，如果我用分类标签作为订阅链接，两个不同的标签分类下会出现同一个视频。这个会重复下载么？因为视频会根据分类放在不同的文件夹

如果视频放在配置的**下载目录或者下载目录的子目录下**，不会重复下载。否则会重复下载。

所以你的不同的**文件夹还是需要是下载目录的子目录**，并且视频的文件名不能修改。检测重复只会在下载目录下递归搜索来避免重复下载。。

**Comment by sewujishipin** [comment]
@2niuhe   谢谢作者百忙之中解答~  我随后写个程序，采集jable每个视频网址自动分类去重写入您的下载工具中，到时候我会分享至github。
