### ISSUE TITLE
老哥可以增加多线程下载么，一个文件一个文件下载好慢。。

### ISSUE THREAD

**Issue by sewujishipin** [2niuhe/jable_downloader#9]
老哥可以增加多线程下载么，一个文件一个文件下载好慢。。

**Comment by 2niuhe** [comment]
> 老哥可以增加多线程下载么，一个文件一个文件下载好慢。。

服务器对访问频率限制了，客户端多线程没意义。

想提速可以多进程，多执行几个下载进程，估计不会有什么提升。
